@startuml
'https://plantuml.com/class-diagram
hide empty members

class Any
class "Any?"

class MyInt #green
class "MyInt?" #green

class Nothing
class "Nothing?"

Any <|-- MyInt
MyInt <|-- Nothing

"Any?" <|-- "MyInt?"
"MyInt?" <|-- "Nothing?"

Any .right.|> "Any?": подтип
MyInt .right.|> "MyInt?": подтип
Nothing .right.|> "Nothing?": подтип


@enduml